version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env

    networks:
      - localhost
  test-db:
    image: postgres:latest
    ports:
      - 5435:5432
    env_file:
      - .env.test
    networks:
      - localhost

networks:
  localhost:
